repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
