title: PaddleLabel
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://paddlecv-sig.github.io/PaddleLabel/

# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
