openapi: 3.0.0
info:
  title: PP-Label API Spec
  version: 0.1.0
  description: ''
servers:
  - url: 'http://localhost:5000/api'
    description: Local server
paths:
  /projects:
    get:
      tags:
        - Project
      summary: 'Read all projects, sort by last modify date'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      tags:
        - Project
      summary: Create a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
            examples:
              Classfication Example:
                value:
                  name: Classification Example
                  description: Example Project Descreption
                  task_category: 1
                  data_dir: ~/pplabel/project_dir/data
                  label_dir: ~/pplabel/project_dir/label
                  label_config: '[''class1'', ''class2'', ''class3'']'
                  other_settings: '{''multiclass_classification'':true}'
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
              examples:
                example-1:
                  value:
                    project_id: 0
                    name: Example Project
                    description: Example Descreption
                    task_category: 1
                    data_dir: ~/pplabel/project_dir/data
                    label_dir: ~/pplabel/project_dir/label
                    label_config: string
                    created: string
                    modified: string
                    other_settings: string
      parameters:
        - schema:
            type: string
          in: header
          name: request_id
          description: 'Assign a unique random value each run, server will reject requests with duplicate request_id within several seconds. Prevent critical operations from running multiple times'
  '/projects/{project_id}':
    get:
      tags:
        - Project
      summary: Get info of a specific project
      parameters:
        - name: project_id
          in: path
          description: Id of the project
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not fond
    delete:
      summary: Delete a project record and ALL TASKS RECORDS under the project.
      description: Delete a project record and ALL TASKS RECORDS under the project. Won't delete file on file system
      tags:
        - Project
      parameters:
        - name: project_id
          in: path
          description: Id of the project to delete
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: The task specified is not found
    put:
      tags:
        - Project
      summary: Edit project info
      description: Edit project info. Provide key value pair to change one value only. Provide all changed values to change multiple. Empty string will be set. Leave values don't intend to change out of request body.
      parameters:
        - name: project_id
          in: path
          description: Id of the project to edit
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/Project'
                - $ref: '#/components/schemas/KeyValuePair'
            examples:
              Full Project:
                value:
                  name: Change All Info
                  description: Example Project Descreption
                  task_category: 1
                  data_dir: ~/pplabel/project_dir/data
                  label_dir: ~/pplabel/project_dir/label
                  label_config: '[''class1'', ''class2'', ''class3'']'
                  other_settings: '{''multiclass_classification'':true}'
              One Property:
                value:
                  name: Change Only Project Name
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: 'Project with project id not fond, or project dont have requested property'
  /tasks:
    get:
      tags:
        - Task
      summary: 'Get all tasks, sort by last modified'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    post:
      tags:
        - Task
      summary: Create a new task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: success
  '/tasks/{task_id}':
    get:
      tags:
        - Task
      summary: Get info of a specific task
      parameters:
        - name: task_id
          in: path
          description: Id of the task
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not fond
    delete:
      summary: Delete a task and ALL DATA and ANNOTATIONS under the task.
      description: Delete a task and ALL DATA and ANNOTATIONS under the project. Won't delete file on file system
      tags:
        - Task
      parameters:
        - name: task_id
          in: path
          description: Id of the task to delete
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: The task specified is not found
    put:
      tags:
        - Task
      summary: Edit task info
      description: Edit task info. Provide key value pair to change one value only. Provide all changed values to change multiple. Empty string will be set. Leave values don't intend to change out of request body.
      parameters:
        - name: task_id
          in: path
          description: Id of the task to edit
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/Task'
                - $ref: '#/components/schemas/KeyValuePair'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: 'Task with task id not fond, or task dont have requested property'
  /datas/:
    get:
      tags:
        - Data
      summary: 'Get all data, sort by last modified'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
    post:
      tags:
        - Data
      summary: Create a new data record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
      parameters:
        - schema:
            type: string
          in: header
          name: request_id
          description: 'Assign a unique random value each run, server will reject requests with duplicate request_id within several seconds. Prevent critical operations from running multiple times'
  '/datas/{data_id}':
    get:
      tags:
        - Data
      summary: Get info of a specific data record
      parameters:
        - name: data_id
          in: path
          description: Id of the data record
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
        '404':
          description: Data record not fond
    delete:
      summary: Delete a data record
      description: 'Delete a data record, file on file system will not be deleted'
      tags:
        - Data
      parameters:
        - name: data_id
          in: path
          description: Id of the data record to delete
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: The data record specified is not found
    put:
      tags:
        - Data
      summary: Edit data record
      description: Edit data record. Provide key value pair to change one value only. Provide all changed values to change multiple. Empty string will be set. Leave values don't intend to change out of request body.
      parameters:
        - name: data_id
          in: path
          description: Id of the data record to edit
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/Data'
                - $ref: '#/components/schemas/KeyValuePair'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
        '404':
          description: 'Data record with data id not fond, or data dont have requested property'
  /annotations/:
    get:
      tags:
        - Annotation
      summary: 'Get all annotations, sort by last modified'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Annotation'
    post:
      tags:
        - Annotation
      summary: Create a new annotation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Annotation'
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotation'
      parameters:
        - schema:
            type: string
          in: header
          name: request_id
          description: 'Assign a unique random value each run, server will reject requests with duplicate request_id within several seconds. Prevent critical operations from running multiple times'
  '/annotations/{annotation_id}':
    get:
      tags:
        - Annotation
      summary: Get info of a specific annotation
      parameters:
        - name: annotation_id
          in: path
          description: Id of the annotation
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotation'
        '404':
          description: Annotation not fond
    delete:
      summary: Delete an annotation
      description: Delete an annotation
      tags:
        - Annotation
      parameters:
        - name: annotation_id
          in: path
          description: Id of the annotation to delete
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: The annotation record specified is not found
    put:
      tags:
        - Annotation
      summary: Edit annotation
      description: Edit annotation. Provide key value pair to change one value only. Provide all changed values to change multiple. Empty string will be set. Leave values don't intend to change out of request body.
      parameters:
        - name: annotation_id
          in: path
          description: Id of the annotation to edit
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/Annotation'
                - $ref: '#/components/schemas/KeyValuePair'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotation'
        '404':
          description: 'Annotation record with data id not fond, or data dont have requested property'
components:
  schemas:
    Project:
      type: object
      description: Contains project details and settings
      x-examples:
        Classification_Example:
          project_id: null
          name: Classification Example
          description: Example Project Descreption
          task_category: 1
          data_dir: ~/pplabel/project_name/data
          label_dir: ~/pplabel/project_name/label
          label_config: '[''class1'', ''class2'', ''class3'']'
          created: null
          modified: null
          other_settings: '{''multiclass_classification'':true}'
      additionalProperties: false
      properties:
        project_id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
          description: Project name
        description:
          type: string
          description: Optional project description
        task_category:
          type: integer
          maximum: 64
          description: 'Top level annotation task category, see TODO for int <-> category map'
        data_dir:
          type: string
          description: Absolute directory path where all the data file is stored
        label_dir:
          type: string
          description: Absolute directory path where all the label files are stored
        label_config:
          type: string
          description: Label configuration. Varies across different task categories
        created:
          type: string
          description: Project creation timestamp in UTC
          format: timestamp
          nullable: true
          readOnly: true
        modified:
          type: string
          description: Last time the project detail or ANY TASK of the project is modified
          format: timestamp
          nullable: true
          readOnly: true
        other_settings:
          type: string
          description: Project settings that are different across annotation task categories
      required:
        - name
        - task_category
        - data_dir
    Task:
      title: Task
      type: object
      description: An annotation task
      additionalProperties: false
      properties:
        task_id:
          type: integer
          readOnly: true
        project_id:
          type: integer
        datas:
          type: array
          items:
            $ref: '#/components/schemas/Data'
          readOnly: true
        annotations:
          type: array
          items:
            $ref: '#/components/schemas/Annotation'
        project:
          $ref: '#/components/schemas/Project'
        modified:
          type: string
          format: timestamp
          readOnly: true
        created:
          type: string
          format: timestamp
          readOnly: true
      required:
        - project_id
    Data:
      title: Data
      type: object
      properties:
        data_id:
          type: integer
          readOnly: true
        task_id:
          type: integer
        path:
          type: string
        slice_count:
          type: integer
        task:
          $ref: '#/components/schemas/Task'
        created:
          type: string
          readOnly: true
        modified:
          type: string
          readOnly: true
      required:
        - path
    Annotation:
      title: Annotation
      type: object
      description: ''
      properties:
        annotation_id:
          type: integer
          readOnly: true
        label_id:
          type: integer
        result:
          type: string
        slice_id:
          type: integer
        task:
          $ref: '#/components/schemas/Task'
        modified:
          type: string
          readOnly: true
        created:
          type: string
          readOnly: true
    KeyValuePair:
      description: A key-value pair
