title: PaddleLabel
description: An effective and flexible tool for data annotation
theme: just-the-docs

url: https://paddlecv-sig.github.io/
baseurl: "/PaddleLabel"

permalink: pretty

search_enabled: false
heading_anchors: true

aux_links: # remove if you don't want this link to appear on your pages
  项目 Github: https://github.com/PaddleCV-SIG/PaddleLabel
