name: Build PaddleLabel package

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  update_doc_build:
    uses: PaddleCV-SIG/PaddleLabel/.github/workflows/doc_to_pages.yml@develop
    with:
      baseurl: "/static/doc/"
      deploy: false

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    needs: update_doc_build
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Download built frontend
        id: download-built-frontend
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: develop
          repo: PaddleCV-SIG/PaddleLabel-Frontend
          name: PaddleLabel_built_frontend
          path: ./paddlelabel/static/

      - name: Download built doc static site
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          branch: develop
          name: github-pages
          path: ./paddlelabel/static/doc/
          check_artifacts: true

        # uses: actions/download-artifact@v3
        # with:
        #   name: github-pages
        #   path: ./paddlelabel/static/doc/

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade twine wheel

      - name: Write backend commit hash to package
        run: |
          echo backend $(git rev-parse --short HEAD) >> ./paddlelabel/static/git_versions.html

      - name: Generate package
        run: |
          python setup.py sdist bdist_wheel

      - name: Save built package
        uses: actions/upload-artifact@v3
        with:
          name: PaddleLabel_built_package
          path: |
            dist
