name: Build PaddleLabel package

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: develop
          repo: PaddleCV-SIG/PaddleLabel-Frontend
          name: PaddleLabel_built_frontend
          path: |
            built_frontend
      - run: |
          ls
          ls built_frontend

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine wheel
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Bump version
      #   run: |
      #     python tool/bumpversion.py
      #     git config --global user.email "bot@github.com" && git config --global user.name "Action Bot"
      #     git add paddlelabel/version; git commit -m "bump version"; git push

      - name: Write backend commit hash to package
        run: |
          echo backend $(git rev-parse --short HEAD) >> ../git_versions.html

      - name: Copy built frontend and commit hash
        run: |
          mv ../dist/ ./paddlelabel/static/
          mv ../git_versions.html ./paddlelabel/static/

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems
          working-directory: doc/

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Jekyll build
        run: |
          cd doc/
          python prepare.py # insert headers, change md relative link path to html ...
          bundle exec jekyll build \
            --destination ../paddlelabel/static/doc/ \
            --baseurl "/static/doc"

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Save built package
        uses: actions/upload-artifact@v3
        with:
          name: PaddleLabel_built_package
          path: |
            dist
