name: Doc to Pages

on:
  push:
    branches:
      - develop
    inputs:
      source: # id of input
        description: "Path to doc folder"
        required: false
        default: "./doc/"
        type: string
      destination:
        description: "Path to output generated site"
        required: false
        default: "./_site/"
        type: string
      baseurl:
        description: "baseurl of generated site"
        required: false
        default: ""
        type: string
      upload:
        description: "Whether to save generated site as artifact"
        required: false
        default: true
        type: boolean
      force_run:
        description: "Force regenerate"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      source: # id of input
        description: "Path to doc folder"
        required: false
        default: "./doc/"
        type: string
      destination:
        description: "Path to output generated site"
        required: false
        default: "./_site/"
        type: string
      baseurl:
        description: "baseurl of generated site"
        required: false
        default: ""
        type: string
      upload:
        description: "Whether to save generated site as artifact"
        required: false
        default: true
        type: boolean
      force_run:
        description: "Force regenerate"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      source: # id of input
        description: "Path to doc folder"
        required: false
        default: "./doc/"
        type: string
      destination:
        description: "Path to output generated site"
        required: false
        default: "./_site/"
        type: string
      baseurl:
        description: "baseurl of generated site"
        required: false
        default: ""
        type: string
      upload:
        description: "Whether to save generated site as artifact"
        required: false
        default: true
        type: boolean
      force_run:
        description: "Force regenerate"
        required: false
        default: false
        type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      # - uses: dorny/paths-filter@v2
      #   id: changes
      #   with:
      #     filters: |
      #       doc:
      #         - 'doc/**'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems
          # working-directory: doc/

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Jekyll build
        run: |
          echo ${{ inputs.source }}
          echo ${{ inputs.source }}prepare.py
          python ${{ inputs.source }}prepare.py # insert headers, change md relative link path to html ...
          bundle exec jekyll build \
            --source ${{ inputs.source }}
            --destination ${{ inputs.destination }} \
            --baseurl ${{ inputs.baseurl }}
      - name: Upload artifact
        if: ${{ inputs.upload == 'true' }}
        uses: actions/upload-pages-artifact@v1 # This will automatically upload an artifact from the '/_site' directory
        with:
          path: ${{ inputs.destination }}

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
