name: Delete All Caches

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1
        # with:
        #   # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
        #   ref: refs/pull/${{ github.event.number }}/merge
